### PR TITLE
Stable20160913

### PR DESCRIPTION
**Pull request by jbickar**
Updates to contrib and stanford modules and libraries to match the `stable20160913` branch.

### CODE REVIEW

**Comment by jbickar** [comment]
@kbrownell to test:
1. Build a group and a dept site with `drush make make/group.make` and `drush make make/dept.make`
2. Ensure that each build completes successfully with no errors
3. Enstall with `drush si`; use the `install_configure_form.stanford_sites_org_type="dept"` option on the `dept` site
4. Ensure that the dept site gets `stanford_framework` as the default theme
5. Run a handful of Behat tests (pick a few from the modules that were updated) from the `sites/uat` directory. You don't need to run the full suite, just a few to make sure that the installs are good.

**Comment by kbrownell** [comment]
Both builds completed successfully, based on the stable20190913 branch.
And I enabled the stanford_framework theme on the dept site.

It passed the following behat tests:
- admin_menu.feature
- admin_views.feature
- context.feature
- date.feature
- ds.feature
- feeds_xpathparser.feature
- flag.feature
- stanford_courses.feature

Tests the build failed were due to webauth rather than module updates.

**Comment by jbickar** [comment]
👏

**Comment by tsui1** [comment]
_Execute order 66_

**Pull request merged**
