### PR TITLE
7.x 1.0 dev

### PR DESCRIPTION
**Pull request by jbickar**
This is the full 7.x branch, development of which has been done solely in my forked repo.

### CODE REVIEW

**Comment by mistermarco** [comment]
OK to use 7.x-1.x as the branch name?
http://drupal.org/node/1015226

**Comment by jbickar** [comment]
Ah, thanks for finding that. So the fserver would package the most recent commit on the 7.x-1.x branch as 7.x-1.x-dev, as well as packaging all specifically tagged releases?

**Comment by mistermarco** [comment]
Yes, that sounds right.

**Comment by jbickar** [comment]
Well then. Let's do it!

Any idea why it says, "This pull request cannot be automatically merged"?

I'll cancel this pull request, rename the branch, and submit a new one (I think that's the way the workflow needs to go).

**Comment by jbickar** [comment]
Actually, the reason it said "cannot be automatically merged" was because the branch w/in SU-SWS still had 6.x code in it.

**Pull request closed without merging**
