### PR TITLE
Update uuid-7.x-1.1, xmlsitemap-7.x-2.4, stanford_sites_helper-7.x-1.9

### PR DESCRIPTION
**Pull request by jbickar**
Go, Travis.

### CODE REVIEW

**Comment by jbickar** [comment]
Not sure what's up with Travis.

**Comment by sherakama** [comment]
The @javascript login is broken again. Our override method signature isn't matching whatever version we are using.

**Comment by sherakama** [comment]
Our behat files need a whole bunch of updates that I don't have time for. How comfortable do you feel about these versions not breaking functionality?

**Comment by jbickar** [comment]
We've already deployed them to production on over 2,000 websites, so I'd say my comfort level is pretty high.

**Comment by jbickar** [comment]
Behat worked for me, FYI. So it's something giving Travis a sad.

**Comment by sherakama** [comment]
When is the last time you updated your composer packages?

**Comment by jbickar** [comment]
For linky_clicky? What year is it now?

**Comment by jbickar** [comment]
You *do* know that I was on El Capitan until a few weeks ago, right?

**Pull request merged**
