### PR TITLE
Updated auto_nodetitle to a dev commit

### PR DESCRIPTION
**Pull request by sherakama**
Commit hash includes empty token replacement fix.
Re: https://www.drupal.org/node/1123266

### CODE REVIEW

**Comment by sherakama** [comment]
@jbickar FYI.

**Comment by jbickar** [comment]
I'm confused why we're not seeing this issue more consistently. I was not able to reproduce it reliably when I encountered it a few weeks ago.

**Comment by sherakama** [comment]
It showed up for me on my local builds often but I did not see it too often on sites. Possibly the error reporting level was too low?

**Comment by jbickar** [comment]
When you say "error reporting level was too low" I am thinking maybe you are confusing this PR with https://github.com/SU-SWS/stanford_install_tasks/pull/33

**Comment by sherakama** [comment]
The issue was reproduced by creating a new node manually. CAPx could map data directly to the title field and would bypass the auto_nodetitle functionality. 

When creating a new node DO NOT enter any data in to the title (Display Name) field.

**Comment by jbickar** [comment]
This was the Behat test that I got inconsistent results from:

https://github.com/SU-SWS/linky_clicky/blob/5.x/sites/uat/features/stanford_person.feature

```
@stanford
Feature: Stanford Person
  In order to ensure that upgrades do not break existing functionality
  As an administrative user
  I want to ensure that the Stanford Person module is working properly

  @api @javascript @content @destructive @dev
  Scenario: Stanford Person
    Given the "stanford_person" module is enabled
    And the "entity_token" module is enabled
    And the cache has been cleared
    And I am logged in as a user with the "administrator" role
    And I am on "node/add/stanford-person"
    When I enter "Leland" for "First name *"
    And I enter "Stanford" for "Last Name *"
    And I press the "Save" button
    Then I should be on "people/leland-stanford"
    And I should see "Person Leland Stanford has been created"
```

It failed a couple of times, and then it passed. Tried to reproduce on a clean install with only this test, and it passed. Sounds like it's time to re-try this test.

**Comment by sherakama** [comment]
@kbrownell ping.

**Comment by sherakama** [comment]
sherakama: Were you able to get the test to consistently pass?
kbrownell: Yes, when run by itself.

**Pull request merged**
