### PR TITLE
BASIC-1468: Dev version release for stanford_framework

### PR DESCRIPTION
**Pull request by sherakama**
Update stanford_framework to include recent bug fixes.

### CODE REVIEW

**Comment by jbickar** [comment]
The Curse of the JBs continues unabated.

**Comment by jbickar** [comment]
I am getting these errors and don't know why. Can you reproduce?

```
Unable to clone stanford_jordan from git@github.com:SU-SWS/stanford_jordan.git.                                                                                                                                        [error]
Unable to clone stanford_framework from git@github.com:SU-SWS/stanford_framework.git.                                                                                                                                  [error]
```

**Comment by sherakama** [comment]
@jbickar,

Those are still working for me. Nothing around those have changed in the PR. Check your access to the repository and try running again with the `--verbose` option.

**Comment by jbickar** [comment]
with `drush 7.0-dev`. OK I'll try a different drush version.

**Comment by jbickar** [comment]
```
ERROR: Sorry, but @SU-SWS has blocked access to SSH keys created by some third-party applications. Your key was created before GitHub tracked keys created by applications, so we need your help.
```

That 'splains it.

**Pull request merged**
