### PR TITLE
Update to stanford_framework-7.x-3.5

### PR DESCRIPTION
**Pull request by jbickar**

### CODE REVIEW

**Comment by jbickar** [comment]
Go Travis. It's your birthday.

**Comment by jbickar** [comment]
`jbickagdpr-stanford-framework-7.x-3.5r-patch-4` What is this I don't even

**Comment by sherakama** [comment]
You and Travis have the same birthday!

**Comment by jbickar** [comment]
🙄

**Comment by jbickar** [comment]
Travis failure is because of https://stanfordits.atlassian.net/browse/DEVOPS-123

**Comment by jbickar** [comment]
Copypasta is hard.

**Review by sherakama — APPROVED** [review]

**Pull request merged**
