### PR TITLE
7.x-2.5

### PR DESCRIPTION
**Pull request by jbickar**
# READY FOR REVIEW

# Summary
- New tagged release

# Needed By (Date)
- This week would be awesome (by March 10th), but might not happen due to Drupal Camp.

# Urgency
- Needed for pushing updates to Anchorage

# Steps to Test

1. Build `group.make`
2. Build `dept.make`

Ignore the failing tests on Travis. We're working on cleaning those up.

# Affected Projects or Products
- Anchorage updates

# Associated Issues and/or People
- #75

### CODE REVIEW

**Comment by sherakama** [comment]
Hey, all tests pass. That is niiiiIIiiiiiiccce.

**Comment by sherakama** [comment]
I'm running Travis again as some tests failed after the latest commit.

**Comment by jbickar** [comment]
@kbrownell and I are planning a working session this Thursday to beat our recalcitrant Behat tests into submission, so that Travis will only fail when it should. https://github.com/SU-SWS/linky_clicky/pull/139 is part of that effort.

**Comment by sherakama** [comment]
Ah ok, as long as I am not undermining the tests by merging this.

**Comment by jbickar** [comment]
Yeah, I think Travis integration got added before all the tests were verified working. So we're breaking from best practice at the moment, but need to set it right.

**Comment by sherakama** [comment]
It passed the first time through...

**Comment by sherakama** [comment]
Oh, that was just CC. Gotcha. Catching up. Ignore the Canadian.

**Comment by jbickar** [comment]
I usually do.

**Pull request merged**
