### PR TITLE
7.x 1.x

### PR DESCRIPTION
**Pull request by jbickar**
Let's try this.

### CODE REVIEW

**Comment by mistermarco** [comment]
Got these errors when trying to merge:
CONFLICT (delete/modify): CHANGELOG.txt deleted in HEAD and modified in 2fd5f7d160a431de22ed8d1a811c1b9c492c063e. Version 2fd5f7d160a431de22ed8d1a811c1b9c492c063e of CHANGELOG.txt left in tree.
CONFLICT (delete/modify): README.txt deleted in HEAD and modified in 2fd5f7d160a431de22ed8d1a811c1b9c492c063e. Version 2fd5f7d160a431de22ed8d1a811c1b9c492c063e of README.txt left in tree.
CONFLICT (delete/modify): stanford.make deleted in HEAD and modified in 2fd5f7d160a431de22ed8d1a811c1b9c492c063e. Version 2fd5f7d160a431de22ed8d1a811c1b9c492c063e of stanford.make left in tree.
CONFLICT (delete/modify): stanford.profile deleted in HEAD and modified in 2fd5f7d160a431de22ed8d1a811c1b9c492c063e. Version 2fd5f7d160a431de22ed8d1a811c1b9c492c063e of stanford.profile left in tree.

Doing this manually...

**Comment by mistermarco** [comment]
Done!

**Comment by jbickar** [comment]
You're a good man.

And thorough.

**Comment by mistermarco** [comment]
I just pulled in all the great changes you've done. You're the good man! Thanks!

**Comment by jbickar** [comment]
It doesn't look like it pulls in tags from a forked version. I guess that makes sense, but still: sad clown.

**Pull request closed without merging**
