### PR TITLE
Stable20161206

### PR DESCRIPTION
**Pull request by kbrownell**
Let me know if these versions look correct based on: https://docs.google.com/spreadsheets/d/1gcywuj_LErJtzU9vfbr5g5stq_KrEQAJYO7w7gp7Qgg/edit#gid=2045289217.  Note: Shea requested we use this jw_player commit instead of version 2.0-beta2: https://github.com/SU-SWS/stanford-jumpstart-deployer/blob/7.x-5.x/development/product/jumpstart-engineering/contrib.make#L221 because 2.0-beta2 does not include patch: https://www.drupal.org/files/issues/jw-player-mysql57-2713921-8.patch.

### CODE REVIEW

**Comment by jbickar** [comment]
`group.make` and `dept.make` both build and install successfully.

**Comment by jbickar** [comment]
Compared versions against the spreadsheet, and ensured that nothing unwanted snuck in either.

**Comment by sherakama** [comment]
Is drafty a new dependency of the workflow modules or just a cool new contrib module?

**Comment by kbrownell** [comment]
Drafty is required by the latest version of workbench_moderation: 
screen shot 2016-12-13 at 2 10 41 pm

**Pull request merged**
